version: '3.0'
services:
  app:
    build:
      context: ./project
      dockerfile: ./../docker/Dockerfile
    image: my-laravel-app
    container_name: excel-jobs-app
    restart: unless-stopped
    depends_on:
      - database
    environment:
      DB_CONNECTION: mysql
      DB_HOST: database
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD: secret
      XDEBUG_CONFIG: "client_host=host.docker.internal remote_port=9003"
      PHP_IDE_CONFIG: "serverName=localhost"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "80:80"
      - "443:443"
      - "9090:9090"
      - "5173:5173"
      - "8000:8000"
    volumes:
      - ./project:/var/www/html
      - ./docker/config/php/php.ini:/usr/local/etc/php/php.ini
  database:
    image: mysql:5.7
    container_name: excel-jobs-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
    volumes:
      - ./docker/mysql:/var/lib/mysql
      - ./config/init.db:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
  redis:
    image: redis
    container_name: redis-server
    restart: always
    volumes:
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./docker/redis/data:/data
    ports:
      - "6379:6379"
